### ISSUE TITLE
Roadmap for v3.1, Upcoming Release

### ISSUE THREAD

**Issue by erlend-sh** [jMonkeyEngine/jmonkeyengine#199]
This is our open roadmap for a **v3.1**, due to be released in early 2015.

Non-blocking items may be moved to "Future Release" - #198 - if the upcoming Stable Release is imminent. (Make them bold after moving).
#### Legend

**Bold** - Must-have.
## Infrastructure Improvements
- [x] **New build system for the engine based on Gradle as opposed to ant.**
- [x] New repository stored on GitHub
- [ ] Move plugins repositories to GitHub
- [x] **Embed version number & GIT version into jars’ manifest and into the JmeVersion class - this must occur automatically on every build.**
- [ ] Rolling nightly builds (no need to manually delete old builds), nice web UI to show releases.
- [ ] **Nightly build updates online javadoc - no more outdated javadoc**
## Core Engine Improvements
- [x] Physically Based Rendering
  - [ ] Energy-conserving blinn-phong specular
  - [x] Gloss map support
  - [x] gamma correct rendering
  - [x] HDR with filmic tone mapping
  - [x] FXAA post-process
- [ ] Native libraries to perform functions which require native code for performance (especially for embedded platforms like Android / iOS)
  - [x] Vorbis audio decoding
  - [x] Texture decoding
  - [ ] Software skinning
  - [x] **Bullet Physics**
  - [ ] **OpenGL binding**
  - [x] **OpenAL binding**
  - [ ] JInput (static linking could potentially be limited by license)
  - [ ] WebM (VP9 / Vorbis) video decoding (optional)
- [X] **Shift the render-system abstraction away from the Renderer interface into a GL interface which can then be implemented in a much more lean manner. URA!**
  - [x] **The GL interface can be implemented by various classes such as LwjglGL, JoglGL, AndroidGL, IOSGL. Do the same for OpenAL.**
## com.jme3.post
- [x] HDR really should be required for any post processing system.
## com.jme3.system
- [x] Native extraction should be completely controlled by the context implementation, it should occur when Application requests it. `JmePlatform.initialize()` must not extract natives (maybe remove completely?).

**Comment by shadowislord** [comment]
Closing since 3.1 is already released
