### ISSUE TITLE
3.1 release roadmap

### ISSUE THREAD

**Issue by shadowislord** [jMonkeyEngine/jmonkeyengine#315]
#### Version
- [X] Decide on a version format
- [X] Implement version format in build script. Extract version from Git tag.
#### Maven
- [X] Build maven artifacts
- [X] Publishing maven artifacts to updates server
  - [ ] Fix maven dependency issue with jbullet
- [x] Test maven artifacts
#### Distribution
- [X] Build distribution package
- [x] Test distribution package
- [x] Publishing distribution package to GitHub
#### Javadoc
- [ ] Publish javadoc to updates server
#### Nightly / Stable Updates
- [X] Build NBM files
- [X] Version format
  - [X] Determine "specification version" based on engine version + Git revision
  - [X] Determine "implementation version"
- [X] Publish NBMs to updates server
- [X] Test SDK updates
#### Installers
- [X] Fix permission issues on Linux
- [X] Build installer for Linux x64
- [X] Build installer for Linux x86
- [X] Build installer for Mac OS X
- [X] Build installer for Windows x64
- [X] Build installer for Windows x86

**Comment by erlend-sh** [comment]
> Determine if 32-bit installers are required

I'd say just don't include them for the alpha/beta releases, and then we can gauge how many people are missing them.

**Comment by pspeed42** [comment]
A couple of my boxes are still WinXP 32 bit and I'd like to continue using
them for a while with JME.

**Comment by erlend-sh** [comment]
Yeah, I just checked our download statistics and it seems pretty foolhardy to exclude 32 bit.

**Comment by shadowislord** [comment]
Version format has been implemented in 17887b1fb0c1478808a6aee5dc441cb59d1b5975

**Comment by shadowislord** [comment]
There's a weird issue plaguing the Linux installer. The executables in the folders `jdk/jre/bin` and `blender` are missing proper executable (+x) permissions, hence there's an access denied error when the jME SDK tries to use them. It seems that those permissions are being stripped upon being inserted into the `data,1.jar` package which is injected into the installer. 

Another issue is with the packaging of the JDK for Windows - it seems the `rt.jar.pack.gz` file is not being properly unpacked upon installation, hence that file has to be bundled without any compression as `rt.jar`. 

At this point, we may need to ask ourselves if there's a point to including the JDK? After all, we expect users to be experienced Java developers in order to use the engine. Isn't it expected that experienced Java developers will have the JDK installed? 

I am going to go ahead and loop in @normen on this so he can participate.

**Comment by normen** [comment]
Some reasons for this were incompatible JDKs on computers (Apple JDK on OSX, OpenJDK on Linux) as well as recurring troubleshooting requests of people who didn't have a JDK (or just a JRE). Additionally having a known JDK bundled with the SDK narrows down the range of issues people might have.

**Comment by phr00t** [comment]
Is there a way to just "chmod +x" those files in an installation script post install?

I've recently switched back to Windows (VR development and all), but I'm pretty certain I developed on OpenJDK without issue for quite some time on Linux. I wouldn't let including the JDK on Linux hold up its release. Installing & maintaining a JDK is as simple as "sudo apt-get install openjdk-8" etc.

**Comment by shadowislord** [comment]
@phr00t 
Actually I realized yesterday that changing the permissions after copying the files is the NetBeans Platform preferred way of having a bundled JVM. I was very surprised, I didn't think NetBeans platform would steep that low to support this.. I hoped there would be a more reasonable alternative. 
So looks like that problem is solved.

**Comment by normen** [comment]
Btw, you can do all kinds of things in the config logic of the installer:
https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/sdk/nbi/stub/ext/components/products/helloworld/src/org/mycompany/ConfigurationLogic.java <https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/sdk/nbi/stub/ext/components/products/helloworld/src/org/mycompany/ConfigurationLogic.java>

**Comment by normen** [comment]
Oh I just see you did exactly that ^^

**Comment by shadowislord** [comment]
There's another issue with the helpset generation not working correctly. The help pages are pulled correctly from the wiki but the links are incorrect. However since this issue can be resolved via NBM updates it will not be a blocker for the initial installer release.

**Comment by shadowislord** [comment]
An update:
Installers underwent closed testing. Some issues were found and corrected. NBM updates are confirmed working as well. The next round will be an open test. Better get ready @erlend-sh

**Comment by shadowislord** [comment]
Another update:
Maven snapshot artifacts are now published automatically to updates.jmonkeyengine.org. They will be published as a release artifact if it is a tagged commit.

**Comment by shadowislord** [comment]
Closing since 3.1 was already released
