### ISSUE TITLE
SDK issue checklist

### ISSUE THREAD

**Issue by shadowislord** [jMonkeyEngine/jmonkeyengine#329]
(Note: consider splitting these into separate issues)

 - [ ] The bundled Blender 2.75a is not supported - exported models crash the SDK. One option is to simply update to an older Blender version such as 2.74.
 - [ ] Projects from 3.0 SDK are not compatible with 3.1 SDK. For example, native deployment and names of the libraries have changed - hence recreating the project is required.
 - [ ] The built-in documentation which is generated from the wiki has broken links - the generator has not been adjusted to the new wiki structure yet. As a result, the welcome page still says "You're using the latest version of jMonkeyEngine SDK (3.0)"
 - [X] The terrain editor no longer works correctly - erasing a texture does not work. Also the paint brush seems to be offset a bit from where the mouse is. Fixed in edd183a2be86af90f5bea680fc2b953d8bf0177f
 - [ ] In the "Projects" tab, importing a new asset causes it to be selected under "Dependencies" instead of under "Assets".
 - [ ] The editor is based on NetBeans 8.0, but NetBeans 8.1 has already been released.

**Comment by grizeldi** [comment]
Which of those have been fixed so far? I might see if I can help later this week.

**Comment by MeFisto94** [comment]
Well, I am currently working on porting to 8.1 (it compiles, I only have to fix some warnings).
The Blender Issue has been solved (afaik, atleast it doesn't crash anymore)

So it would be nice if you could look into that projects thing or the imported projects (though I am uncertain with that: Should we simply overwrite the old lib names with the new ones, or maybe have consistent lib names (If possible))

**Comment by grizeldi** [comment]
So today I managed to fix the most trivial (welcome to jme3.0) one. PR follows as soon as I figure out how to make a build of SDK and test it out.
For really complex stuff you can't really count on me because I lack of programming experience and more important: time.

**Comment by grizeldi** [comment]
Just checked the documentation generator and it also seems to be updated to the "now not so new anymore" wiki structure.
With that I think #3 is done when/if my PR is accepted.

**Comment by grizeldi** [comment]
I mean number 3 on the list not issue #3... Darn github do you have to auto detect issues -.-

**Comment by erlend-sh** [comment]
This issue was moved to jMonkeyEngine/sdk#7
